[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
launch_pad = "7GKWqKvkev22SYs2HEb1jw6h4uHJwLVKpEcxVUqTZKxG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yow/.config/solana/id.json"

[test]
startup_wait =20000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
